name: SonarQube Analysis

on:
  push:
    branches:
      - DE-55463-SonarQubeIntegration
  pull_request:
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, sockets
      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run phpstan
        run: composer phpstan

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composer-arg:
          - "install"
          - "update --prefer-lowest"
        php-version:
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, sockets
      - name: Install dependencies
        run: composer ${{ matrix.composer-arg }} --prefer-dist
      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Debug Information
        run:
          php --version
          composer --version
          cat composer.json
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonar.nice.com"
