name: SonarQube Analysis

on:
  push:
    branches:
      - DE-55463-SonarQubeIntegration
  pull_request:
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, sockets
      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPUnit tests and Generate covwerage report
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --testdox
        
  sonarqube:
    runs-on: ubuntu-latest
    needs: phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonar.nice.com"
